import type { Metadata } from "next";
import { Poppins, Roboto_Condensed } from "next/font/google";
import "./globals.css";

const FontPoppins = Poppins({
  variable: "--poppins",
  weight: ["600"],
});

const FontRoboto_Condensed = Roboto_Condensed({
  variable: "--robotoCondensed",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${FontPoppins.variable} ${FontRoboto_Condensed.variable}`}
      >
        <div className="container">{children}</div>
      </body>
    </html>
  );
}
